"""Experimental state-based ISO synthesis package."""

from .model import (
    EvidenceSource,
    IsoStateEvaluation,
    IsoStatePlan,
    IsoStateSynthesisError,
    IsoStateWarning,
    StageDifferential,
    StateStage,
    StateChange,
    StateValue,
    StateVector,
    TraceMove,
    TracePoint,
    to_jsonable,
)
from .catalog import (
    BLOCKS,
    TRANSITIONS,
    IsoBlockDefinition,
    IsoTransitionDefinition,
    block_id_for_stage_key,
    head_for_family,
    select_transition_id,
    transition_id_for_rule_status,
)
from .pgmx_source import build_state_plan_from_pgmx, build_state_plan_from_snapshot
from .differential import evaluate_pgmx_state_plan, evaluate_state_plan
from .emitter import (
    ExplainedIsoLine,
    ExplainedIsoProgram,
    IsoCandidateComparison,
    IsoCandidateEmissionError,
    IsoLineDifference,
    compare_candidate_to_iso,
    emit_candidate_for_pgmx,
    emit_candidate_from_evaluation,
)

__all__ = [
    "BLOCKS",
    "ExplainedIsoLine",
    "ExplainedIsoProgram",
    "EvidenceSource",
    "IsoBlockDefinition",
    "IsoCandidateComparison",
    "IsoCandidateEmissionError",
    "IsoLineDifference",
    "IsoStateEvaluation",
    "IsoStatePlan",
    "IsoStateSynthesisError",
    "IsoStateWarning",
    "IsoTransitionDefinition",
    "StageDifferential",
    "StateStage",
    "StateChange",
    "StateValue",
    "StateVector",
    "TRANSITIONS",
    "TraceMove",
    "TracePoint",
    "block_id_for_stage_key",
    "build_state_plan_from_pgmx",
    "build_state_plan_from_snapshot",
    "compare_candidate_to_iso",
    "emit_candidate_for_pgmx",
    "emit_candidate_from_evaluation",
    "evaluate_pgmx_state_plan",
    "evaluate_state_plan",
    "head_for_family",
    "select_transition_id",
    "transition_id_for_rule_status",
    "to_jsonable",
]
